name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # change based on your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean up stale Chrome profiles
        run: rm -rf /tmp/selenium* /tmp/profile* /tmp/tmp*

      - name: Run tests
        run: |
          pytest --browser_name chrome --html=report.html
